all:
	gcc uart_diagnostic.c -o uart_diagnostic.o
	gcc usb_read.c -o usb_read.o
	gcc uart_read.c -o uart_read.o
	gcc lets_try_this_again.c -o again.o

clean:
	rm uart_diagnostic.o
	rm usb_read.o
	rm uart_read.o
	rm again.o